[[headers]]
  for = "/assets/docs/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/pdf"
    Content-Disposition = "inline"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200