[build]
  publish = "/"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

 [[headers]]
    for = "/src/assets/docs/*"
      [headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Type = "application/pdf"
      Content-Disposition = "attachment; filename=:splat"
      X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/docs/*"
  to = "/src/assets/docs/:splat"
  status = 200
  force = true

[[redirects]]
    from = "/docs/*"
    to = "/src/assets/docs/:splat"
    status = 200
    force = true
