[[headers]]
  for = "/src/assets/docs/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'"

[[redirects]]
  from = "/src/assets/docs/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200