[[headers]]
  for = "/src/assets/docs/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    Content-Disposition = "attachment"

[[redirects]]
  from = "/docs/*"
  to = "/src/assets/docs/:splat"
  status = 200
  force = true

  [build]
    publish = "/"

  [[headers]]
    for = "/*"
      [headers.values]
      Access-Control-Allow-Origin = "*"

  [[headers]]
    for = "/src/assets/docs/*"
      [headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      Content-Disposition = "attachment"
      X-Content-Type-Options = "nosniff"
      Access-Control-Allow-Methods = "GET, OPTIONS"
      Cache-Control = "public, max-age=0"

  [[redirects]]
    from = "/docs/*"
    to = "/src/assets/docs/:splat"
    status = 200
    force = true

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200