[[headers]]
  for = "/src/assets/docs/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/pdf"
    Content-Disposition = "inline"

[[redirects]]
  from = "/docs/*"
  to = "/src/assets/docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
